/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace AuctionBids {
  export type AuctionBidContextStruct = {
    bidderAddress: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
  };

  export type AuctionBidContextStructOutput = [string, BigNumber] & {
    bidderAddress: string;
    price: BigNumber;
  };
}

export interface AuctionBidsInterface extends utils.Interface {
  functions: {
    "getHighestBid()": FunctionFragment;
    "pushBids((address,uint256))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getHighestBid" | "pushBids"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getHighestBid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushBids",
    values: [AuctionBids.AuctionBidContextStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHighestBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pushBids", data: BytesLike): Result;

  events: {};
}

export interface AuctionBids extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AuctionBidsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getHighestBid(overrides?: CallOverrides): Promise<[BigNumber]>;

    pushBids(
      newBid: AuctionBids.AuctionBidContextStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getHighestBid(overrides?: CallOverrides): Promise<BigNumber>;

  pushBids(
    newBid: AuctionBids.AuctionBidContextStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getHighestBid(overrides?: CallOverrides): Promise<BigNumber>;

    pushBids(
      newBid: AuctionBids.AuctionBidContextStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getHighestBid(overrides?: CallOverrides): Promise<BigNumber>;

    pushBids(
      newBid: AuctionBids.AuctionBidContextStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHighestBid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushBids(
      newBid: AuctionBids.AuctionBidContextStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
