/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auction from "./Auction";
export type { auction };
export type { MarketplaceFeeTaker } from "./MarketplaceFeeTaker";
