/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MoneySenderToTreasury } from "./MoneySenderToTreasury";
export type { PausebleOnlyOwner } from "./PausebleOnlyOwner";
